# Generated by Django 3.0.6 on 2020-05-17 18:44

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, help_text='First Name', max_length=120)),
                ('last_name', models.CharField(default=None, help_text='First Name', max_length=120)),
                ('email', models.EmailField(default=None, help_text='Email Address', max_length=254, unique=True)),
                ('country_code', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Name of Plan', max_length=120)),
                ('billing_interval', models.CharField(choices=[('MONTH', 'Monthly'), ('YEAR', 'Yearly')], default=None, help_text='Billing Interval', max_length=20)),
                ('frequency', models.CharField(default=None, help_text='Invoice Frequency', max_length=120)),
                ('currency', models.CharField(default=None, help_text='Cost Currency', max_length=3)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='custreg.CustomerRegistration')),
            ],
        ),
    ]
