version: "3"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${POSTGRESQL_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - ${POSTGRESQL_PORT}:${POSTGRESQL_PORT}
  django:
    build: ./backreg
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    volumes:
      - ./backreg:/app/django
    environment:
      - DB_HOST=postgres
      - DB_PORT=${POSTGRESQL_PORT}
      - DB_USER=${POSTGRESQL_DB_USER}
      - DB_NAME=${POSTGRESQL_DB_USER}
      - DB_PASS=${POSTGRESQL_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    depends_on:
      - postgres
  frontreg:
    build: ./frontreg
    command: npm run start
    # This setting solves a little issue with react-scripts
    stdin_open: true
    volumes:
      - ./frontreg:/app/frontreg
      - node-modules:/app/frontreg/node_modules
    ports:
      - ${SPA_PORT}:${SPA_PORT}

volumes:
  node-modules:
